"""Repository — JSON-based persistence for BookScope analysis results.

Files are stored as:
    {save_dir}/{slug}_{timestamp}.json

where slug is the sanitized book title.

Usage:
    repo = Repository()               # uses ./data/analyses/
    repo = Repository(Path("cache"))  # custom directory

    result = AnalysisResult(...)
    repo.save(result)

    all_results = repo.list_results()
    loaded = repo.load(path)
"""

import re
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel

from bookscope.models import EmotionScore, StyleScore

_DEFAULT_SAVE_DIR = Path("data") / "analyses"


class AnalysisResult(BaseModel):
    """Serializable container for a complete book analysis."""

    book_title: str
    analyzed_at: str             # ISO-8601 UTC timestamp
    chunk_strategy: str
    total_chunks: int
    total_words: int
    arc_pattern: str             # ArcPattern.value string
    detected_lang: str = "en"   # ISO 639-1 language code; defaults to "en" for old saves
    author: str = ""             # optional author name; defaults to "" for old saves
    emotion_scores: list[EmotionScore]
    style_scores: list[StyleScore]

    @classmethod
    def create(
        cls,
        *,
        book_title: str,
        chunk_strategy: str,
        total_chunks: int,
        total_words: int,
        arc_pattern: str,
        detected_lang: str = "en",
        author: str = "",
        emotion_scores: list[EmotionScore],
        style_scores: list[StyleScore],
    ) -> "AnalysisResult":
        return cls(
            book_title=book_title,
            analyzed_at=datetime.now(tz=UTC).isoformat(),
            chunk_strategy=chunk_strategy,
            total_chunks=total_chunks,
            total_words=total_words,
            arc_pattern=arc_pattern,
            detected_lang=detected_lang,
            author=author,
            emotion_scores=emotion_scores,
            style_scores=style_scores,
        )

    def to_csv_emotion(self) -> str:
        """Serialize emotion scores to CSV string."""
        fields = ["chunk_index", "anger", "anticipation", "disgust", "fear",
                  "joy", "sadness", "surprise", "trust"]
        lines = [",".join(fields)]
        for s in self.emotion_scores:
            row = [str(s.chunk_index)] + [f"{getattr(s, f):.6f}" for f in fields[1:]]
            lines.append(",".join(row))
        return "\n".join(lines)

    def to_markdown_report(self) -> str:
        """Generate a human-readable Markdown analysis report."""
        from collections import Counter

        _EMOTION_FIELDS = ("anger", "anticipation", "disgust", "fear",
                           "joy", "sadness", "surprise", "trust")

        lines: list[str] = []
        lines.append(f"# BookScope Analysis Report: {self.book_title}\n")
        lines.append(f"**Analysed at:** {self.analyzed_at}  ")
        lines.append(f"**Chunking strategy:** {self.chunk_strategy}  ")
        lines.append(f"**Total chunks:** {self.total_chunks}  ")
        lines.append(f"**Total words:** {self.total_words:,}  ")
        lines.append(f"**Emotional arc:** {self.arc_pattern}\n")

        # Dominant emotion
        if self.emotion_scores:
            dominants = Counter(s.dominant_emotion for s in self.emotion_scores)
            top_emotion, top_count = dominants.most_common(1)[0]
            lines.append("---\n")
            lines.append("## Emotion Summary\n")
            lines.append(
                f"**Dominant emotion:** {top_emotion.capitalize()} "
                f"({top_count}/{len(self.emotion_scores)} chunks)\n"
            )

            # Average scores table
            avg = {
                e: sum(getattr(s, e) for s in self.emotion_scores) / len(self.emotion_scores)
                for e in _EMOTION_FIELDS
            }
            lines.append("| Emotion | Average Score |")
            lines.append("|---------|--------------|")
            for emotion, score in sorted(avg.items(), key=lambda kv: kv[1], reverse=True):
                bar = "█" * int(score * 20)
                lines.append(f"| {emotion.capitalize()} | {score:.4f} {bar} |")
            lines.append("")

        # Style summary
        if self.style_scores:
            lines.append("---\n")
            lines.append("## Style Summary\n")
            n = len(self.style_scores)
            style_fields = ["avg_sentence_length", "ttr", "noun_ratio",
                            "verb_ratio", "adj_ratio", "adv_ratio"]
            lines.append("| Metric | Average |")
            lines.append("|--------|---------|")
            for field in style_fields:
                avg_val = sum(getattr(s, field) for s in self.style_scores) / n
                lines.append(f"| {field.replace('_', ' ').title()} | {avg_val:.4f} |")
            lines.append("")

        lines.append("---\n")
        lines.append("*Generated by [BookScope](https://github.com/bookscope/bookscope)*")
        return "\n".join(lines)

    def to_csv_style(self) -> str:
        """Serialize style scores to CSV string."""
        fields = ["chunk_index", "avg_sentence_length", "ttr",
                  "noun_ratio", "verb_ratio", "adj_ratio", "adv_ratio"]
        lines = [",".join(fields)]
        for s in self.style_scores:
            row = [str(s.chunk_index)] + [f"{getattr(s, f):.6f}" for f in fields[1:]]
            lines.append(",".join(row))
        return "\n".join(lines)


class Repository:
    """Saves and loads AnalysisResult objects to/from JSON files."""

    def __init__(self, save_dir: Path | str = _DEFAULT_SAVE_DIR) -> None:
        self.save_dir = Path(save_dir)

    def save(self, result: AnalysisResult) -> Path:
        """Persist an AnalysisResult to a JSON file.

        Returns the path to the saved file.
        """
        self.save_dir.mkdir(parents=True, exist_ok=True)
        slug = re.sub(r"[^\w\-]", "_", result.book_title)[:40]
        ts = datetime.now(tz=UTC).strftime("%Y%m%dT%H%M%S")
        filename = self.save_dir / f"{slug}_{ts}.json"
        filename.write_text(result.model_dump_json(indent=2), encoding="utf-8")
        return filename

    def load(self, path: Path | str) -> AnalysisResult:
        """Load an AnalysisResult from a JSON file."""
        return AnalysisResult.model_validate_json(Path(path).read_text(encoding="utf-8"))

    def list_results(self) -> list[Path]:
        """Return all saved analysis files, newest first."""
        if not self.save_dir.exists():
            return []
        return sorted(self.save_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)

    def delete(self, path: Path | str) -> None:
        """Delete a saved analysis file."""
        Path(path).unlink(missing_ok=True)

    # ── Reading diary (sidecar notes) ────────────────────────────────────────

    def save_notes(self, analysis_path: Path | str, notes: dict) -> None:
        """Persist notes dict as a sidecar JSON file next to the analysis.

        Notes are stored at ``{stem}_notes.json`` alongside the analysis file.
        Keys: mood_score (int|None), memorable_quote (str), read_date (str).
        """
        import json
        p = Path(analysis_path)
        notes_path = p.with_name(p.stem + "_notes.json")
        notes_path.write_text(json.dumps(notes, ensure_ascii=False, indent=2), encoding="utf-8")

    def load_notes(self, analysis_path: Path | str) -> dict:
        """Load sidecar notes for an analysis file.

        Returns an empty dict (backward-compatible) when no notes file exists.
        """
        import json
        p = Path(analysis_path)
        notes_path = p.with_name(p.stem + "_notes.json")
        if not notes_path.exists():
            return {}
        try:
            return json.loads(notes_path.read_text(encoding="utf-8"))
        except Exception:
            return {}
