"""BookScope — Read-only share view for publicly shared analyses.

Rendered when the app is opened with ``?share={slug}`` in the URL.
Shows a stripped-down, read-only presentation: title, metadata, emotion
radar, valence arc, and style radar — no upload, no sidebar controls.
"""

import html as _html

import streamlit as st

from bookscope.nlp.arc_classifier import ArcClassifier
from bookscope.store.supabase_repository import SupabaseRepository
from bookscope.viz.chart_data_adapter import ChartDataAdapter
from bookscope.viz.emotion_radar_renderer import EmotionRadarRenderer
from bookscope.viz.style_radar import StyleRadarRenderer

_EMOTION_COLORS = {
    "anger": "#ef4444", "anticipation": "#f97316", "disgust": "#84cc16",
    "fear": "#8b5cf6",  "joy": "#facc15",          "sadness": "#60a5fa",
    "surprise": "#f472b6", "trust": "#34d399",
}


def render_share_view(slug: str, T: dict, ui_lang: str) -> None:
    """Render a read-only shared analysis page.

    Args:
        slug:    8-character share slug from the URL query param.
        T:       Localised string dictionary for the current UI language.
        ui_lang: UI language code (``"en"`` / ``"zh"`` / ``"ja"``).
    """
    repo = SupabaseRepository()

    if not repo.available:
        st.error(T.get("share_view_not_found", "This analysis is not available."))
        st.caption(
            "Supabase is not configured on this instance. "
            "Set SUPABASE_URL and SUPABASE_KEY to enable sharing."
        )
        return

    result = repo.load_by_slug(slug)

    if result is None:
        st.error(T.get("share_view_not_found", "This analysis doesn't exist or isn't public."))
        return

    # ── Title + metadata ─────────────────────────────────────────────────────
    st.markdown(
        f"<h1 style='margin-bottom:.25rem;'>📖 {_html.escape(result.book_title)}</h1>",
        unsafe_allow_html=True,
    )
    author = getattr(result, "author", "").strip()
    meta_parts = []
    if author:
        meta_parts.append(_html.escape(author))
    meta_parts += [
        result.analyzed_at[:10],
        f"{result.total_words:,} {T.get('hero_words', 'words').lower()}",
        result.arc_pattern,
    ]
    st.caption(" · ".join(meta_parts))

    st.divider()

    # ── Emotion radar ─────────────────────────────────────────────────────────
    if result.emotion_scores:
        radar_data = ChartDataAdapter.build_emotion_radar_data(
            result.emotion_scores, _EMOTION_COLORS
        )
        radar_fig = EmotionRadarRenderer().render(radar_data)
        col_radar, col_arc = st.columns(2)
        with col_radar:
            st.plotly_chart(radar_fig, use_container_width=True)

        # ── Valence arc ───────────────────────────────────────────────────────
        with col_arc:
            arc_classifier = ArcClassifier()
            valence = arc_classifier.valence_series(result.emotion_scores)
            if len(valence) >= 2:
                import plotly.graph_objects as go

                x = [i / (len(valence) - 1) for i in range(len(valence))]
                fig_arc = go.Figure()
                fig_arc.add_trace(
                    go.Scatter(
                        x=x, y=valence,
                        mode="lines",
                        line=dict(color="#a78bfa", width=2),
                        fill="tozeroy",
                        fillcolor="rgba(167,139,250,0.10)",
                        hovertemplate="%{y:.3f}<extra></extra>",
                    )
                )
                fig_arc.update_layout(
                    template="plotly_dark",
                    paper_bgcolor="#0d1117",
                    plot_bgcolor="#0d1117",
                    title=dict(text=result.arc_pattern, font=dict(color="#e6edf3")),
                    xaxis=dict(
                        title=T.get("arc_valence_caption", "Position"),
                        tickformat=".0%",
                        gridcolor="#21262d",
                        showgrid=True,
                    ),
                    yaxis=dict(gridcolor="#21262d", showgrid=True),
                    margin=dict(l=40, r=20, t=50, b=40),
                    height=300,
                )
                st.plotly_chart(fig_arc, use_container_width=True)

    # ── Style radar ───────────────────────────────────────────────────────────
    if result.style_scores:
        style_data = ChartDataAdapter.style_radar(result.style_scores)
        style_fig = StyleRadarRenderer().render(style_data)
        st.plotly_chart(style_fig, use_container_width=True)

    # ── Footer ────────────────────────────────────────────────────────────────
    st.divider()
    st.caption(T.get("share_view_footer", "Generated by BookScope"))
